/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PeleadoresRouteImport } from './routes/peleadores'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as GimnasiosRouteImport } from './routes/gimnasios'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as PeleadoresIdRouteImport } from './routes/peleadores.$id'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as AdminFightersRouteImport } from './routes/admin.fighters'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PeleadoresRoute = PeleadoresRouteImport.update({
  id: '/peleadores',
  path: '/peleadores',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const GimnasiosRoute = GimnasiosRouteImport.update({
  id: '/gimnasios',
  path: '/gimnasios',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeleadoresIdRoute = PeleadoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeleadoresRoute,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFightersRoute = AdminFightersRouteImport.update({
  id: '/admin/fighters',
  path: '/admin/fighters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gimnasios': typeof GimnasiosRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/peleadores': typeof PeleadoresRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/admin/fighters': typeof AdminFightersRoute
  '/eventos/$id': typeof EventosIdRoute
  '/peleadores/$id': typeof PeleadoresIdRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gimnasios': typeof GimnasiosRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/peleadores': typeof PeleadoresRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/admin/fighters': typeof AdminFightersRoute
  '/eventos/$id': typeof EventosIdRoute
  '/peleadores/$id': typeof PeleadoresIdRoute
  '/eventos': typeof EventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gimnasios': typeof GimnasiosRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/peleadores': typeof PeleadoresRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/admin/fighters': typeof AdminFightersRoute
  '/eventos/$id': typeof EventosIdRoute
  '/peleadores/$id': typeof PeleadoresIdRoute
  '/eventos/': typeof EventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/feed'
    | '/gimnasios'
    | '/noticias'
    | '/onboarding'
    | '/peleadores'
    | '/perfil'
    | '/admin/fighters'
    | '/eventos/$id'
    | '/peleadores/$id'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/feed'
    | '/gimnasios'
    | '/noticias'
    | '/onboarding'
    | '/peleadores'
    | '/perfil'
    | '/admin/fighters'
    | '/eventos/$id'
    | '/peleadores/$id'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/auth'
    | '/feed'
    | '/gimnasios'
    | '/noticias'
    | '/onboarding'
    | '/peleadores'
    | '/perfil'
    | '/admin/fighters'
    | '/eventos/$id'
    | '/peleadores/$id'
    | '/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  GimnasiosRoute: typeof GimnasiosRoute
  NoticiasRoute: typeof NoticiasRoute
  OnboardingRoute: typeof OnboardingRoute
  PeleadoresRoute: typeof PeleadoresRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  AdminFightersRoute: typeof AdminFightersRoute
  EventosIdRoute: typeof EventosIdRoute
  EventosIndexRoute: typeof EventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peleadores': {
      id: '/peleadores'
      path: '/peleadores'
      fullPath: '/peleadores'
      preLoaderRoute: typeof PeleadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gimnasios': {
      id: '/gimnasios'
      path: '/gimnasios'
      fullPath: '/gimnasios'
      preLoaderRoute: typeof GimnasiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peleadores/$id': {
      id: '/peleadores/$id'
      path: '/$id'
      fullPath: '/peleadores/$id'
      preLoaderRoute: typeof PeleadoresIdRouteImport
      parentRoute: typeof PeleadoresRoute
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fighters': {
      id: '/admin/fighters'
      path: '/admin/fighters'
      fullPath: '/admin/fighters'
      preLoaderRoute: typeof AdminFightersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PeleadoresRouteChildren {
  PeleadoresIdRoute: typeof PeleadoresIdRoute
}

const PeleadoresRouteChildren: PeleadoresRouteChildren = {
  PeleadoresIdRoute: PeleadoresIdRoute,
}

const PeleadoresRouteWithChildren = PeleadoresRoute._addFileChildren(
  PeleadoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  GimnasiosRoute: GimnasiosRoute,
  NoticiasRoute: NoticiasRoute,
  OnboardingRoute: OnboardingRoute,
  PeleadoresRoute: PeleadoresRouteWithChildren,
  PerfilRoute: PerfilRoute,
  AdminFightersRoute: AdminFightersRoute,
  EventosIdRoute: EventosIdRoute,
  EventosIndexRoute: EventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
